- usernames/aayush-fadia.txt
This is the new way in which we will collect their usernames, everyone makes a new file in the usernames folder, named <username>.txt, and in that file, will be their real name.
We will merge their PRs
> Added usernames folder and demo file.

- github_usernames.txt
added my username in github_username.txt
> Aditya's commit

- usernames/take2rohit.txt
please merge admin 
PLEASE!!!!!!!!
> added rohit's username

- usernames/AdityaWadichar.txt
> added username AdityaWadichae

- usernames/ZeoDarkflame.txt
- usernames/akshansh-malviya.txt
> Name Changed to UserName

- usernames/divydividivu.txt
> added github username.txt to usernames

- repeat.txt
> steps to contribute

- usernames/name.txt
> name added

- ABD-01
- code.py
- usernames/ABD-01.txt
> First Pull

- usernames/VedantPhuse.txt
Please merge my username into the folder
> added my username to the folder

- usernames/sibam23.txt
> Added my username

- usernames/path-of-tan.txt
> My username

- usernames/Sahil-18.txt
> Added Sahil-18

- usernames/Kshitij-Ambilduke.txt
> Entered Kshitij's name

- usernames/SonOfADev.txt
pls merge added Aneesh's username
> added Aneesh's username

- usernames/nilakshi.txt
> added name

- usernames/priyansh-design.txt
please merge request
Please!!!
> added file name priyansh-design

- kar-tik.txt
- usernames/kar-tik.txt
> Added my name

- usernames/Ajay7Saraf.txt
please merge my file
PLEASE!!!!!
> Added my file into usernames

- usernames/sushlokshah.txt
> sushlok's file

- tushar_c.txt
> please merge admin

- usernames/Diksha_Bagade.txt
> Wrote my name

- usernames/RiteshZoad.txt
> added username

- usernames/ak07-lab.txt
@ak07-lab your file is not in proper directory. Please change directory
> Revert "Create ak07-lab.txt"

- usernames/voldar.txt
> vondar.txt

- usernames/riyadshpande
> riyadshpande

- code.py
- usernames/codernakul.txt
created codernakul.txt and added favourite movie line in code.py
> codernakul's Task

- usernames/Rutvik1728.txt
> Added Rutvik1728.txt

- usernames/Pratyush_Chakraborty.txt
added my name and git username
> Added Pratyush_Chakraborty.txt

- usernames/BUZZLi8tYear.txt
> added username.txt

- usernames/omkharat.txt
> Added OmKharat786.txt

- usernames/thisisgarvithedaoo.txt
added favourite movie name in code.py and created thisisgarvithedaoo.txt in usernames folder
> thisisgarvithedaoo's task

- usernames/tphanir.txt
> Added tphanir.txt

- AkhileshNavalkar.txt
Reverts IvLabs/learn-to-use-github#116
> Revert "create AkhileshNavalkar.txt"
